### ISSUE TITLE
beacon parser crashes after phone rotation.

### ISSUE THREAD

**Issue by murrayk** [edina/floorplan-viewer#3]

**Comment by murrayk** [comment]
Caused by: java.lang.IllegalArgumentException: Service not registered: org.altbeacon.beacon.BeaconManager$1@38fcfbc4
            at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1029)
            at android.app.ContextImpl.unbindService(ContextImpl.java:1947)
            at android.content.ContextWrapper.unbindService(ContextWrapper.java:551)
            at uk.ac.edina.floorplan.MainActivity.unbindService(MainActivity.java:220)
            at org.altbeacon.beacon.BeaconManager.unbind(BeaconManager.java:304)
            at uk.ac.edina.floorplan.MainActivity.onDestroy(MainActivity.java:270)

**Comment by murrayk** [comment]
Known bug .
https://github.com/AltBeacon/android-beacon-library/issues/139

suggestion is just to catch Exception till bugfix
